name: housing
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.7
  flutter_login_facebook: ^1.1.0
  http: ^0.13.3
  flutter_switch: ^0.3.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  permission_handler: ^10.0.0
  images_picker: ^1.2.11
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope.ttf
          weight: 400
        - asset: assets/fonts/ManropeExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Readex Pro
      fonts: 
        - asset: assets/fonts/ReadexProRegular.ttf
          weight: 400
